### ISSUE TITLE
[공지] 유체크 관련

### ISSUE THREAD

**Issue by unizard** [sejongresearch/2019.Fall.AdvancedC#125]
이메일을 통해 신청한 출결이 모두 처리 되었습니다.

출결에 이상이 있는 친구들은 내일 오후 12시까지 이메일을 통해 이의신청해주세요.

출결 변경요청시, 본인이 해당 시간에 수업에 참여했었다는 OJ 기록을 캡쳐하여 보내주시기 바랍니다.

**Comment by EesunMoon** [comment]
11월 27일에 지각한거 교수님한테 캡쳐해서 신청했습니다!!
12월 16일 이론 시간에 시험보느라 잊어버리고 유체크를 못했습니다!!!

2019년 12월 18일 (수) 오후 5:16, Yukyung Choi <notifications@github.com>님이 작성:

**Comment by unizard** [comment]
@eesun-1018 이메일로 신청해주세요~
