### ISSUE TITLE
[공지]  보강 수업  공지 (10/21)

### ISSUE THREAD

**Issue by unizard** [sejongresearch/2019.Fall.AdvancedC#56]
## 보강 관련 내용
- 9월 9일 휴강에 대한 보강을 10월 21일 실시합니다.
- 수업은 시험과 관련된 질의 응답으로 이루어집니다.
- 첨석은 선택입니다. 9월 9일에 대한 출결은 모두 출석으로 반영됩니다.
- 참석 의사에 대한 사전신청을 "필수"로 진행하니,  신청바랍니다.

## 보강 신청 방법
- 신청마감일: 10월 18일 오후 6시
- 이메일: ykchoi@sejong.ac.kr
- 제목: 아래와 같이 신청바랍니다.
  - [고급C] 10월 21일 이론 참석합니다.
  - [고급C] 10월 21일 실습 참석합니다.
  - [고급C] 10월 21일 이론/실습 참석합니다.

**Comment by unizard** [comment]
## 보강 신청자
- 강민정, 김영규, 김연우, 김인우, 김현지, 김현지, 박정곤, 송혜원, 심주미, 이재표

**Comment by EesunMoon** [comment]
교수님... 오제이가 어제부터 안되는데 이거 어떻게 해야하나요.....

2019년 10월 19일 (토) 오후 3:02, Yukyung Choi <notifications@github.com>님이 작성:
